### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jiumohoo** [Gantzyo/ChronoGG-clicker-PHP#1]
Can you help me to install php script? I don't understand how it works. Did same things like for Saliens (steam) script but nothing happened. Will be cool if you add full instructruction in description README.md

**Comment by Gantzyo** [comment]
Just copy **script** folder wherever you want and run **script/chronogg-clicker/runAll.php**. Remember to configure your accounts.json
It's explained under [configuration](https://github.com/Gantzyo/ChronoGG-clicker-PHP#configuration) section

**Comment by jiumohoo** [comment]
Open with? https://i.imgur.com/LG6mjUL.png
Opened with cgi and got rss https://i.imgur.com/uB65PvI.png this is good? Too much info and  i see "Already clicked" seems works. 
Also need to turn on or turn off (extension=curl / ;extension=curl)? I don't know what is it 👀

**Comment by Gantzyo** [comment]
Yup, that's working fine!
I'm closing this "issue" since this isn't directly related with this script, but with your php configuration and how to run a php script. Also, it looks like you aren't using an RSS reader and you are running it locally so you may prefer to manually check results.json every once in a while (It's way easier to read!)
